---
deployment:
  tasks:
    - export DEPLOYPATH=/home/adaptive/
    # - export DEPLOYPATH=/home/adaptive/public_html/
    # - /bin/cp index.html $DEPLOYPATH
    # - /bin/cp style.css $DEPLOYPATH
    # - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R commands $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R controllers $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R mail $DEPLOYPATH
    - /bin/cp -R models $DEPLOYPATH
    - /bin/cp -R tests $DEPLOYPATH
    - /bin/cp -R vagrant $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
    - /bin/cp -R web $DEPLOYPATH
    - /bin/cp -R web/* /home/adaptive/public_html/
    - /bin/cp -R widgets $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH